<section id="licensing">
  <h1>Licensing & Sponsorship</h1>
  <p>Bullseye2D's core is licensed under the <span class="hl">MIT License</span>, offering <span class="hl">freedom</span> to use, modify, and distribute your games.

  </p>
  <p>For advanced features and to <span class="hl">support the project</span>, we offer a <span class="hl">Premium Edition</span>. Purchasing a license gives access to extra features and fuels Bullseye2D's ongoing development. Premium features may transition to the MIT core over time.</p>
  <p>But all important things you need to build and publish games are for <span class="hl">free</span> in the MIT core; a license is <span class="hl">no requirement.</span></p>

  <details class="licensing-accessibility">
    <summary>
      <h4>Get the premium edition for free</h4>
    </summary>
    <div class="details-content">
      <p>Game development should be accessible to everyone. If any of the following apply to you, simply email Jochen at <span class="email-placeholder"></span> with a short note — you’ll receive access to the Premium Edition for free.
      </p>
      <ul>
        <li>You're a <span class="hl">hobbyist</span> not earning income from your projects (please outline your project).</li>
        <li>You're <span class="hl">under 18</span>.</li>
        <li>You're a <span class="hl">student</span> (school, college, bootcamp, or online course)</li>
        <li>You're a <span class="hl">teacher, mentor, or parent</span> teaching kids to code.
        </li>
        <li>You work(ed) in <span class="hl">public service</span> or for a <span class="hl">non-profit organization</span>.</li>
      </ul>
    </div>
  </details>

  <div class="pricing-columns-3">
    <article class="pricing-card">
      <h3>🧡 Premium Edition</h3>
      <div class="hl">One time purchase</div>
      <div class="price">$79</div>
      <p>Perfect for <span class="hl">individual developers</span> or <span class="hl">small teams</span> who want to support the project and gain early access to advanced features.</p>
      <hr>
      <ul>
        <li>Full access to <strong>Premium Edition</strong></li>
        <li><strong>1 year of updates</strong> (Perpetual license)</li>
        <li>up to <strong>3 developer seats</strong></li>
        <li>Build and publish <strong>unlimited games</strong></li>
        <li>You help fund future development</li>
      </ul>
      <form action="./checkout/create-session/premium" method="POST">
        <button type="submit" class="button">Get Premium Edition</button>
      </form>
    </article>

    <article class="pricing-card">
      <h3>🏆 Gold Sponsor</h3>
      <div class="hl">Monthly subscription</div>
      <div class="price">$129<span> / month</span></div>
      <p>For <span class="hl">studios</span> and <span class="hl">companies</span> who want to actively support Bullseye2D and help shape it's future.
      </p>
      <hr>
      <ul>
        <li>All <strong>Premium Edition</strong> benefits</li>
        <li>Logo placement (<strong>Gold Tier</strong>)<br /><span class="subnote">on website and GitHub README</span></li>
        <li><strong>Priority bug fixes</strong> and <strong>feature requests</strong></li>
        <li><strong>Direct help</strong> via email (fair use)</li>
        <li>Recognition as a <strong>Gold Sponsor</strong></li>
      </ul>
      <form action="./checkout/create-session/gold" method="POST">
        <button type="submit" class="button">Become a Gold sponsor</button>
      </form>
    </article>

    <article class="pricing-card">
      <h3>💎 Platinum Sponser</h3>
      <div class="hl">Monthly subscription</div>
      <div class="price">$299<span> / month</span></div>
      <p>For teams who want to <span class="hl">deeply support</span> Bullseye2D's growth.</p>
      <hr>
      <ul>
        <li>All <strong>Premium Edition</strong> benefits</li>
        <li>Logo placement (<strong>Platinum Tier</strong>)<br /><span class="subnote">on website and GitHub README</span></li>
        <li><strong>Highest priority</strong> for bugs and <strong>features</strong></li>
        <li><strong>Private support channel</strong> (email/Discord)</li>
        <li>Recognition as a <strong>top-tier sponsor</strong></li>
      </ul>
      <form action="./checkout/create-session/platinum" method="POST">
        <button type="submit" class="button">Become a Platinum sponsor</button>
      </form>
    </article>
  </div>
</section>
