            <main>
                <div class="container">
                    <section id="imprint-content">
                        <h1>Imprint</h1>

                        <address style="font-style: normal;">
                            Asylum Square Interactive GmbH<br>
                            Oberer Hummelberg 1<br>
                            D-72275 Alpirsbach<br>
                            Germany
                        </address>

                        <p><strong>CEO:</strong>
                            Jochen Heizmann<br />

                            <strong>Contact:</strong> <span class="email-placeholder"></span>

                        <p><strong>Commercial Register:</strong><br>
                            Amtsgericht Stuttgart, HRB 748721</p>

                        <p><strong>VAT Identification Number (USt-IdNr.):</strong><br>
                            DE294768853</p>

                        <h2>Third-Party Software & Licenses</h2>
                        <p>
                            This website uses <a href="https://highlightjs.org/" target="_blank">Highlight.js</a> for syntax highlighting of code examples.
                            Highlight.js is distributed under the BSD 3-Clause License.
                        </p>
                        <p>
                            The routing functionality of this website is powered by <a href="https://github.com/dannyvankooten/AltoRouter" target="_blank">AltoRouter</a>.
                            AltoRouter is distributed under the MIT License.
                        </p>
                        <p>
                            Mails are sent through <a href="https://github.com/PHPMailer/PHPMailer">PHPMailer</a> - the classic email sending library for PHP.
                        <p>
                        <p>
                            <a href="https://github.com/stripe/stripe-php">Stripe</a> is used for providing the checkout process.
                        </p>
                        <p>
                            The following fonts are used on this website:
                        <ul>
                            <li><strong>Inter</strong> by Rasmus Andersson, licensed under the <a href="https://scripts.sil.org/OFL" target="_blank">SIL Open Font License</a>.</li>
                            <li><strong>Fira Code</strong> by The Fira Code Project Authors, licensed under the <a href="https://scripts.sil.org/OFL" target="_blank">SIL Open Font License</a>.</li>
                        </ul>
                        <p>This website itself is open source and licensed under the MIT License. You can find the source code on <a href="https://github.com/bullseye2d/bullseye2d.org" target="_blank">GitHub</a>.</p>
                        <h2>Privacy Policy</h2>
                        <p>This privacy policy is for the website and apps from Asylum Square Interactive GmbH.</p>

                        <p><strong>Our Core Privacy Principles:</strong></p>
                        <ul>
                            <li>We <strong>don't</strong> collect your personal data just for browsing our site or using our apps.</li>
                            <li>We <strong>don't</strong> share your data unless it's essential (like for a purchase).</li>
                            <li>We <strong>don't</strong> use ads or trackers.</li>
                        </ul>

                        <p>Here’s how we handle information in specific situations:</p>

                        <h3>Contacting Us</h3>
                        <p>If you email us (e.g., for help), we'll use your email address and any info you provide just to respond to you. We don't use it for anything else.</p>

                        <h3>Buying Something from Us</h3>
                        <p>If you buy something, we'll need some info to process your order, like your name, address, email, and what you ordered.
                            Your payment details (like credit card numbers) are handled directly and securely by our trusted payment partners (e.g., Stripe, PayPal). We <strong>don't</strong> store these sensitive payment details ourselves.
                            We use your purchase information only to complete your transaction, provide support if needed, and for essential record-keeping (like for taxes). We only share what's necessary with our payment partners to make this happen. We will <strong>not</strong> use this information for unrelated marketing unless you explicitly say it's okay.</p>

                        <h3>Security</h3>
                        <p>We take reasonable steps to keep things secure. For purchases, your sensitive payment information is protected by our payment partners. Since we generally collect very little personal data, your risk on our end is minimal.</p>

                        <h3>Your Consent</h3>
                        <p>By using our website or apps, or by making a purchase, you agree to this policy.</p>

                        <h3>Questions?</h3>
                        <p>If you have any questions about our privacy approach, please

                            <span class="email-placeholder">contact us</span>
                            .
                        </p>

                    </section>
                </div>
            </main>
