<footer class="site-footer" id="page-footer">
  <div class="container">
    <div class="footer-social-links">
      <a href="{links.github}" target="_blank" aria-label="GitHub">
        <svg aria-hidden="true" focusable="false" viewBox="0 0 24 24">
          <use href="#icon-github"></use>
        </svg></a>
      <a href="{links.discord}" target="_blank" aria-label="Discord">
        <svg aria-hidden="true" focusable="false" viewBox="0 0 24 24">
          <use href="#icon-discord"></use>
        </svg></a>
      <a href="{links.youtube}" target="_blank" aria-label="YouTube">
        <svg aria-hidden="true" focusable="false" viewBox="0 0 16 16">
          <use href="#icon-youtube"></use>
        </svg></a>
    </div>
    <p>© Copyright {currentYear} by Asylum Square Interactive GmbH</p>
    <p><a href="./imprint">Imprint</a> | <a href="./terms">Terms of Service</a></p>
  </div>
</footer>
</body>

</html>
